// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdaYN0B5U4Sg785HlZGmg-Z8sKcXNaKOk',
    appId: '1:1079022557174:web:b2e0108d0874dd7717d9d7',
    messagingSenderId: '1079022557174',
    projectId: 'smart-app-bc41d',
    authDomain: 'smart-app-bc41d.firebaseapp.com',
    storageBucket: 'smart-app-bc41d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD1GlT3qitNb1pGACJH_VsyQTqgh2XEqU',
    appId: '1:1079022557174:android:89a5811f6feed00e17d9d7',
    messagingSenderId: '1079022557174',
    projectId: 'smart-app-bc41d',
    storageBucket: 'smart-app-bc41d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ZBpQRfKc1wz9m21973EcLg1oPNqw_yA',
    appId: '1:1079022557174:ios:eba3f2df513b6a8117d9d7',
    messagingSenderId: '1079022557174',
    projectId: 'smart-app-bc41d',
    storageBucket: 'smart-app-bc41d.firebasestorage.app',
    iosBundleId: 'com.oubnaali.oubnaaliApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ZBpQRfKc1wz9m21973EcLg1oPNqw_yA',
    appId: '1:1079022557174:ios:eba3f2df513b6a8117d9d7',
    messagingSenderId: '1079022557174',
    projectId: 'smart-app-bc41d',
    storageBucket: 'smart-app-bc41d.firebasestorage.app',
    iosBundleId: 'com.oubnaali.oubnaaliApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdaYN0B5U4Sg785HlZGmg-Z8sKcXNaKOk',
    appId: '1:1079022557174:web:75dfbe56c440797717d9d7',
    messagingSenderId: '1079022557174',
    projectId: 'smart-app-bc41d',
    authDomain: 'smart-app-bc41d.firebaseapp.com',
    storageBucket: 'smart-app-bc41d.firebasestorage.app',
  );
}
